spring.application.name=frontline

spring.datasource.url=jdbc:postgresql://localhost:5432/frontline
spring.datasource.username=postgres

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

jwt.expiration=3600000

logging.level.org.springframework.security=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vaibhavspatil512004@gmail.com
spring.mail.password=jmlp aefs xwjq otcv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true